# Usa una imagen base oficial de Python
FROM python:3.11-slim

# Establece el directorio de trabajo
WORKDIR /backend

# Instalar netcat para usar el comando nc en el entrypoint
RUN apt-get update && apt-get install -y netcat-openbsd && rm -rf /var/lib/apt/lists/*

# Copia el archivo de requerimientos al contenedor
COPY requirements.txt requirements.txt
# Instala las dependencias especificadas en requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copia el código de la aplicación
# Copia todo el contenido de la carpeta actual al directorio de trabajo del contenedor
COPY . .

# Copiar el script entrypoint.sh y asignarle permisos de ejecución
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Expone el puerto 5000 para que Flask sea accesible
EXPOSE 5000

# Configurar el entrypoint para ejecutar migraciones y luego iniciar Flask
ENTRYPOINT ["/entrypoint.sh"]