const testData = [
	{
		id: 1,
		title: "Audio A",
		date: "11.07.21",
		time: "11:30 am",
		season: "Winter",
		duration: "30:45",
		location: "-36 5153.0, 147 1706.8",
		conditions: "Few clouds",
		temperature: "3°C",
		wind: "NNW 11 km/h",
		recordist: "Philip Samartzis",
		notes: "Detailed recording of skiers and snowboarders on Wombat Ramble.",
		tags: ["Birds", "Winter", "Snow"],
		imageUrl: "https://placehold.co/400",
		audioUrl:
			"https://diviextended.com/wp-content/uploads/2021/10/sound-of-waves-marine-drive-mumbai.mp3",
	},
	{
		id: 2,
		title: "Audio B",
		date: "12.07.21",
		time: "2:00 pm",
		season: "Summer",
		duration: "15:20",
		location: "-34 5160.0, 145 1906.8",
		conditions: "Sunny",
		temperature: "25°C",
		wind: "E 5 km/h",
		recordist: "Jane Doe",
		notes: "Recording of beach waves and seagulls near the pier.",
		tags: ["Beach", "Birds", "Nature"],
		imageUrl: "https://placehold.co/400",
		audioUrl:
			"https://diviextended.com/wp-content/uploads/2021/10/sound-of-waves-marine-drive-mumbai.mp3",
	},
	{
		id: 3,
		title: "Audio C",
		date: "13.07.21",
		time: "6:45 am",
		season: "Spring",
		duration: "10:00",
		location: "-35 5140.0, 146 1700.0",
		conditions: "Clear",
		temperature: "12°C",
		wind: "SW 8 km/h",
		recordist: "John Smith",
		notes: "Morning bird songs recorded in the forest.",
		tags: ["Birds", "Nature", "Footsteps"],
		imageUrl: "https://placehold.co/400",
		audioUrl:
			"https://diviextended.com/wp-content/uploads/2021/10/sound-of-waves-marine-drive-mumbai.mp3",
	},
	{
		id: 4,
		title: "Audio D",
		date: "14.07.21",
		time: "5:00 pm",
		season: "Autumn",
		duration: "20:30",
		location: "-37 5120.0, 144 1800.5",
		conditions: "Windy",
		temperature: "18°C",
		wind: "NW 20 km/h",
		recordist: "Emily Clark",
		notes: "Wind whistling through trees in the park.",
		tags: ["Footsteps", "Snow", "Trees"],
		imageUrl: "https://placehold.co/400",
		audioUrl:
			"https://diviextended.com/wp-content/uploads/2021/10/sound-of-waves-marine-drive-mumbai.mp3",
	},
	{
		id: 5,
		title: "Audio E",
		date: "15.07.21",
		time: "8:15 am",
		season: "Winter",
		duration: "25:00",
		location: "-38 5145.0, 143 1755.8",
		conditions: "Snowy",
		temperature: "-5°C",
		wind: "N 10 km/h",
		recordist: "Mark Lee",
		notes: "Sound of snow crunching underfoot.",
		tags: ["Nature", "Snow", "Footsteps"],
		imageUrl: "https://placehold.co/400",
		audioUrl:
			"https://diviextended.com/wp-content/uploads/2021/10/sound-of-waves-marine-drive-mumbai.mp3",
	},
	{
		id: 6,
		title: "Audio F",
		date: "16.07.21",
		time: "10:00 pm",
		season: "Summer",
		duration: "18:10",
		location: "-39 5150.0, 142 1805.0",
		conditions: "Clear night",
		temperature: "22°C",
		wind: "Calm",
		recordist: "Alice Brown",
		notes: "Crickets chirping in a quiet meadow.",
		tags: ["Night", "Snow", "Nature"],
		imageUrl: "https://placehold.co/400",
		audioUrl:
			"https://diviextended.com/wp-content/uploads/2021/10/sound-of-waves-marine-drive-mumbai.mp3",
	},
	{
		id: 7,
		title: "Audio G",
		date: "17.07.21",
		time: "3:30 pm",
		season: "Spring",
		duration: "12:45",
		location: "-40 5142.0, 141 1710.2",
		conditions: "Cloudy",
		temperature: "15°C",
		wind: "W 7 km/h",
		recordist: "Michael Davis",
		notes: "Children playing in the park.",
		tags: ["Nature", "Spring", "Kids"],
		imageUrl: "https://placehold.co/400",
		audioUrl:
			"https://diviextended.com/wp-content/uploads/2021/10/sound-of-waves-marine-drive-mumbai.mp3",
	},
	{
		id: 8,
		title: "Audio H",
		date: "18.07.21",
		time: "11:00 am",
		season: "Autumn",
		duration: "14:30",
		location: "-41 5135.0, 140 1725.0",
		conditions: "Overcast",
		temperature: "10°C",
		wind: "NE 12 km/h",
		recordist: "Sophia Taylor",
		notes: "Rustling leaves in a small grove.",
		tags: ["Autumn", "Summer", "Nature"],
		imageUrl: "https://placehold.co/400",
		audioUrl:
			"https://diviextended.com/wp-content/uploads/2021/10/sound-of-waves-marine-drive-mumbai.mp3",
	},
	{
		id: 9,
		title: "Audio I",
		date: "19.07.21",
		time: "4:30 am",
		season: "Summer",
		duration: "22:15",
		location: "-42 5148.0, 139 1740.8",
		conditions: "Humid",
		temperature: "28°C",
		wind: "E 10 km/h",
		recordist: "Chris Wilson",
		notes: "Ocean waves crashing at dawn.",
		tags: ["Ocean", "Summer", "Waves"],
		imageUrl: "https://placehold.co/400",
		audioUrl:
			"https://diviextended.com/wp-content/uploads/2021/10/sound-of-waves-marine-drive-mumbai.mp3",
	},
	{
		id: 10,
		title: "Audio J",
		date: "20.07.21",
		time: "7:00 pm",
		season: "Winter",
		duration: "19:50",
		location: "-43 5140.0, 138 1755.0",
		conditions: "Snowstorm",
		temperature: "-10°C",
		wind: "SW 30 km/h",
		recordist: "Laura Johnson",
		notes: "Blizzard sounds with howling wind.",
		tags: ["Blizzard", "Waves", "Wind"],
		imageUrl: "https://placehold.co/400",
		audioUrl:
			"https://diviextended.com/wp-content/uploads/2021/10/sound-of-waves-marine-drive-mumbai.mp3",
	},
];

export default testData;
