const testData = [
  {
    id: 1,
    date: "11.07.21",
    time: "11:30 am",
    season: "Winter",
    duration: "30:45",
    location: "-36 5153.0, 147 1706.8",
    conditions: "Few clouds",
    temperature: "3°C",
    wind: "NNW 11 km/h",
    recordist: "Philip Samartzis",
    notes: "Detailed recording of skiers and snowboarders on Wombat Ramble.",
    tags: "Ski, Winter, Snow",
    imageUrl: "https://via.placeholder.com/300x200?text=Audio+1",
    audioUrl: "https://www.example.com/audio1.mp3",
  },
  {
    id: 2,
    date: "12.07.21",
    time: "2:00 pm",
    season: "Summer",
    duration: "15:20",
    location: "-34 5160.0, 145 1906.8",
    conditions: "Sunny",
    temperature: "25°C",
    wind: "E 5 km/h",
    recordist: "Jane Doe",
    notes: "Recording of beach waves and seagulls near the pier.",
    tags: "Beach, Summer, Nature",
    imageUrl: "https://via.placeholder.com/300x200?text=Audio+2",
    audioUrl: "https://www.example.com/audio2.mp3",
  },
  {
    id: 3,
    date: "13.07.21",
    time: "6:45 am",
    season: "Spring",
    duration: "10:00",
    location: "-35 5140.0, 146 1700.0",
    conditions: "Clear",
    temperature: "12°C",
    wind: "SW 8 km/h",
    recordist: "John Smith",
    notes: "Morning bird songs recorded in the forest.",
    tags: "Birds, Morning, Forest",
    imageUrl: "https://via.placeholder.com/300x200?text=Audio+3",
    audioUrl: "https://www.example.com/audio3.mp3",
  },
  {
    id: 4,
    date: "14.07.21",
    time: "5:00 pm",
    season: "Autumn",
    duration: "20:30",
    location: "-37 5120.0, 144 1800.5",
    conditions: "Windy",
    temperature: "18°C",
    wind: "NW 20 km/h",
    recordist: "Emily Clark",
    notes: "Wind whistling through trees in the park.",
    tags: "Wind, Trees, Autumn",
    imageUrl: "https://via.placeholder.com/300x200?text=Audio+4",
    audioUrl: "https://www.example.com/audio4.mp3",
  },
  {
    id: 5,
    date: "15.07.21",
    time: "8:15 am",
    season: "Winter",
    duration: "25:00",
    location: "-38 5145.0, 143 1755.8",
    conditions: "Snowy",
    temperature: "-5°C",
    wind: "N 10 km/h",
    recordist: "Mark Lee",
    notes: "Sound of snow crunching underfoot.",
    tags: "Snow, Winter, Footsteps",
    imageUrl: "https://via.placeholder.com/300x200?text=Audio+5",
    audioUrl: "https://www.example.com/audio5.mp3",
  },
  // Add more entries to reach 10
  {
    id: 6,
    date: "16.07.21",
    time: "10:00 pm",
    season: "Summer",
    duration: "18:10",
    location: "-39 5150.0, 142 1805.0",
    conditions: "Clear night",
    temperature: "22°C",
    wind: "Calm",
    recordist: "Alice Brown",
    notes: "Crickets chirping in a quiet meadow.",
    tags: "Night, Crickets, Calm",
    imageUrl: "https://via.placeholder.com/300x200?text=Audio+6",
    audioUrl: "https://www.example.com/audio6.mp3",
  },
  {
    id: 7,
    date: "17.07.21",
    time: "3:30 pm",
    season: "Spring",
    duration: "12:45",
    location: "-40 5142.0, 141 1710.2",
    conditions: "Cloudy",
    temperature: "15°C",
    wind: "W 7 km/h",
    recordist: "Michael Davis",
    notes: "Children playing in the park.",
    tags: "Playground, Spring, Kids",
    imageUrl: "https://via.placeholder.com/300x200?text=Audio+7",
    audioUrl: "https://www.example.com/audio7.mp3",
  },
  {
    id: 8,
    date: "18.07.21",
    time: "11:00 am",
    season: "Autumn",
    duration: "14:30",
    location: "-41 5135.0, 140 1725.0",
    conditions: "Overcast",
    temperature: "10°C",
    wind: "NE 12 km/h",
    recordist: "Sophia Taylor",
    notes: "Rustling leaves in a small grove.",
    tags: "Leaves, Autumn, Nature",
    imageUrl: "https://via.placeholder.com/300x200?text=Audio+8",
    audioUrl: "https://www.example.com/audio8.mp3",
  },
  {
    id: 9,
    date: "19.07.21",
    time: "4:30 am",
    season: "Summer",
    duration: "22:15",
    location: "-42 5148.0, 139 1740.8",
    conditions: "Humid",
    temperature: "28°C",
    wind: "E 10 km/h",
    recordist: "Chris Wilson",
    notes: "Ocean waves crashing at dawn.",
    tags: "Ocean, Dawn, Waves",
    imageUrl: "https://via.placeholder.com/300x200?text=Audio+9",
    audioUrl: "https://www.example.com/audio9.mp3",
  },
  {
    id: 10,
    date: "20.07.21",
    time: "7:00 pm",
    season: "Winter",
    duration: "19:50",
    location: "-43 5140.0, 138 1755.0",
    conditions: "Snowstorm",
    temperature: "-10°C",
    wind: "SW 30 km/h",
    recordist: "Laura Johnson",
    notes: "Blizzard sounds with howling wind.",
    tags: "Blizzard, Winter, Wind",
    imageUrl: "https://via.placeholder.com/300x200?text=Audio+10",
    audioUrl: "https://www.example.com/audio10.mp3",
  },
];

export default testData;
