"""Add title field to AudioRecordV

Revision ID: 063806d75713
Revises: 603cff744d84
Create Date: 2025-01-19 12:27:24.725806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063806d75713'
down_revision = '603cff744d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('temperature')
        batch_op.drop_column('wind_speed')
        batch_op.drop_column('conditions')
        batch_op.drop_column('recordist')
        batch_op.drop_column('location')
        batch_op.drop_column('notes')
        batch_op.drop_column('image_path')
        batch_op.drop_column('time')
        batch_op.drop_column('wind_direction')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wind_direction', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('time', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('recordist', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('conditions', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('wind_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('title')

    # ### end Alembic commands ###
