"""add model audiorecord test

Revision ID: 4bfd13428fd1
Revises: 2ecd090f0857
Create Date: 2025-01-08 09:54:18.191933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4bfd13428fd1'
down_revision = '2ecd090f0857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_record_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_path', sa.String(length=255), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('audio_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio_record_test')
    # ### end Alembic commands ###
