"""Add new UserAudioMapping model

Revision ID: 603cff744d84
Revises: f2c5aef8e622
Create Date: 2025-01-17 18:28:32.077870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603cff744d84'
down_revision = 'f2c5aef8e622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_audio_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('audio_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audio_id'], ['audio_records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_audio_map')
    # ### end Alembic commands ###
